name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: docker build
      run: docker build -t c_memory_testing .

    - name: push image docker
      run: docker push c_memory_testing

    - name: run test in docker container
      run: docker run c_memory_testing
