name: Docker Container Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "${{ secrets.ivannanavrotska }}"
        password: "${{ secrets.wzd!k4w4YYM_RKw }}"
        
    - name: Build Docker image
      run: docker build -t c_memory_testing .
      
    - name: Run tests
      run: docker run c_memory_testing
